"""Orchestrates the end-to-end creative pipeline for a product.

Pipeline (all provider-agnostic — every step is an interface call):
    1. generate script        (ScriptGenerator)
    2. generate video         (VideoGenerator)
    3. download video locally (VideoStorageService)
    4. upload video           (AdPlatform)
    5. create creative + ad    in the EXISTING ad group (AdPlatform)
    6. persist every artefact and id (repositories)

This service contains the business logic and knows nothing about Gemini, Pexo
or TikTok specifically — only the interfaces injected into it.
"""
from __future__ import annotations

import logging
import os
from dataclasses import dataclass

from app.core.entities import ProductInput, ScriptResult
from app.core.interfaces import AdPlatform, ScriptGenerator, VideoGenerator
from app.database.models import AdStatus
from app.repositories import (
    AdRepository,
    ProductRepository,
    ScriptRepository,
    VideoRepository,
)
from app.services.naming import slugify, video_filename
from app.services.video_storage import VideoStorageService

logger = logging.getLogger("service.creative")


@dataclass(slots=True)
class CreativePipelineResult:
    product_id: int
    script_id: int
    video_id: int
    local_video_path: str
    script_text: str
    script_provider: str
    deployed: bool
    # Populated only when the creative is deployed to the ad platform.
    ad_row_id: int | None = None
    platform_video_id: str | None = None
    creative_id: str | None = None
    ad_id: str | None = None


class CreativeService:
    def __init__(
        self,
        *,
        script_generator: ScriptGenerator,
        video_generator: VideoGenerator,
        ad_platform: AdPlatform,
        storage: VideoStorageService,
        product_repo: ProductRepository,
        script_repo: ScriptRepository,
        video_repo: VideoRepository,
        ad_repo: AdRepository,
        campaign_id: str,
        adgroup_id: str,
        profile_service=None,
        script_strategist=None,
        voiceover=None,
        api_call_repo=None,
        storyboard=None,
        product_cutaway=None,
        captions=None,
        music=None,
        hook_card=None,
        script_qc=None,
        max_script_attempts: int = 3,
    ) -> None:
        self._script_gen = script_generator
        self._video_gen = video_generator
        self._ads = ad_platform
        self._storage = storage
        self._product_repo = product_repo
        self._script_repo = script_repo
        self._video_repo = video_repo
        self._ad_repo = ad_repo
        self._api_calls = api_call_repo
        self._storyboard = storyboard
        self._cutaway = product_cutaway
        self._captions = captions
        self._music = music
        self._hook_card = hook_card
        self._script_qc = script_qc
        self._max_script_attempts = max(1, max_script_attempts)
        self._campaign_id = campaign_id
        self._adgroup_id = adgroup_id
        self._profile_service = profile_service
        # When set, scripts are generated by the profiles-aware Strategist
        # (brand voice, creative directives, angle/hook, novelty) — same as the
        # agent pipeline — so /products/generate and /jobs behave consistently.
        self._strategist = script_strategist
        self._voiceover = voiceover

    def run(
        self,
        product: ProductInput,
        *,
        script_text: str | None = None,
        deploy: bool = True,
        landing_page_url: str | None = None,
    ) -> CreativePipelineResult:
        """Run the creative pipeline.

        Args:
            product: the product to advertise.
            script_text: a prepared script. When provided, the configured
                ScriptGenerator (e.g. Gemini) is SKIPPED and this text is used
                verbatim. Useful for testing with hand-written scripts.
            deploy: when False, stop after the video is generated and
                downloaded — no upload to the ad platform and no ad is created.
                Useful for "generate video only" test runs.
            landing_page_url: optional CTA landing page (deploy path only).
        """
        logger.info(
            "=== Creative pipeline started for '%s' (manual_script=%s deploy=%s) ===",
            product.name,
            script_text is not None,
            deploy,
        )
        slug = slugify(product.name)

        # 0. Persist the product.
        product_row = self._product_repo.create(
            name=product.name,
            slug=slug,
            image_url=product.image_url,
            description=product.description,
            benefits=product.benefits,
        )

        # 1. Script — prepared one if given; else the profiles-aware Strategist
        # (falls back to the bare provider only if no strategist is wired). The
        # script is QC'd HERE, before any video is generated, so a bad script
        # never spends a video-generation API call. A strategist script that
        # fails QC is regenerated up to max_script_attempts; a prepared one is
        # rejected immediately.
        prepared = script_text is not None and bool(script_text.strip())
        can_retry = (not prepared) and (self._strategist is not None)
        attempts = self._max_script_attempts if can_retry else 1
        hook_type = angle = segment = embedding = visual_prompt = None
        for attempt in range(1, attempts + 1):
            hook_type = angle = segment = embedding = visual_prompt = None
            if prepared:
                script = ScriptResult(text=script_text.strip(), provider="manual", model=None)
            elif self._strategist is not None:
                out = self._strategist.generate(product, product_row.id)
                visual_prompt = out.visual_prompt
                script = ScriptResult(
                    text=out.script, provider=out.provider, model=out.model, visual_prompt=visual_prompt
                )
                hook_type, angle, segment, embedding = (
                    out.hook_type, out.angle, out.audience_segment, out.embedding,
                )
            else:
                script = self._script_gen.generate(product)

            if self._script_qc is not None:
                qc = self._script_qc.review(script.text, script.word_count)
                if not qc.ok:
                    logger.info("Pre-video script QC rejected (attempt %d/%d): %s",
                                attempt, attempts, qc.codes)
                    if attempt < attempts:
                        continue
                    from app.core.exceptions import QcRejectedError
                    raise QcRejectedError(reasons=qc.reasons, codes=qc.codes)
            break
        logger.info("Script accepted (%d words): %s", script.word_count, script.text)
        script_row = self._script_repo.create(
            product_id=product_row.id,
            text=script.text,
            provider=script.provider,
            model=script.model,
            word_count=script.word_count,
            hook_type=hook_type,
            angle=angle,
            audience_segment=segment,
            embedding=embedding,
            visual_prompt=visual_prompt,
        )

        # 2. Video.
        directives = self._profile_service.load().creative if self._profile_service else None
        video = self._video_gen.generate(product, script, directives)

        # 3. Download locally, then add the voiceover + merge (if enabled).
        # Providers that bake in their own audio (HeyGen) skip this — merging an
        # ElevenLabs track on top would double the voice.
        file_name = video_filename(slug)
        local_path = self._storage.download(video.download_url, file_name)
        if self._voiceover is not None and not getattr(self._video_gen, "produces_audio", False):
            local_path, file_name = self._voiceover.apply(
                slug=slug, video_path=local_path, file_name=file_name, text=script.text
            )
        # Optional post-step: compose a multi-scene STORY (b-roll under VO).
        if self._storyboard is not None:
            st = self._storyboard.apply(
                local_path, script_text=script.text, duration_seconds=video.duration_seconds,
            )
            if st.path != local_path:
                local_path, file_name = st.path, os.path.basename(st.path)
            if st.logs:
                video.api_calls.extend(st.logs)
        # Optional post-step: briefly cut to a full-screen product shot.
        if self._cutaway is not None:
            cut = self._cutaway.apply(
                local_path, product=product, script_text=script.text,
                duration_seconds=video.duration_seconds,
            )
            if cut.path != local_path:
                local_path, file_name = cut.path, os.path.basename(cut.path)
            if cut.log:  # record the cutaway in the video's API-call log
                video.api_calls.append(cut.log)
        # Optional post-step: burn captions (subtitles) from the script.
        if self._captions is not None:
            cc = self._captions.apply(
                local_path, script_text=script.text, duration_seconds=video.duration_seconds,
            )
            if cc.path != local_path:
                local_path, file_name = cc.path, os.path.basename(cc.path)
            if cc.log:
                video.api_calls.append(cc.log)
        # Optional post-step: mix background music under the narration.
        if self._music is not None:
            mu = self._music.apply(local_path, duration_seconds=video.duration_seconds)
            if mu.path != local_path:
                local_path, file_name = mu.path, os.path.basename(mu.path)
            if mu.log:
                video.api_calls.append(mu.log)
        # Optional post-step (last): prepend a bold hook card before the avatar.
        if self._hook_card is not None:
            hk = self._hook_card.apply(local_path, script_text=script.text)
            if hk.path != local_path:
                local_path, file_name = hk.path, os.path.basename(hk.path)
            if hk.log:
                video.api_calls.append(hk.log)
        video_row = self._video_repo.create(
            product_id=product_row.id,
            script_id=script_row.id,
            provider=video.provider,
            external_job_id=video.external_job_id,
            remote_url=video.download_url,
            local_path=local_path,
            file_name=file_name,
            aspect_ratio=video.aspect_ratio,
            format=video.format,
            duration_seconds=video.duration_seconds,
        )

        # Persist the provider API-call audit trail (payload + params) for this video.
        if self._api_calls is not None and video.api_calls:
            try:
                self._api_calls.record_many(video_row.id, video.api_calls)
            except Exception:  # auditing must never fail the pipeline
                logger.warning("Failed to store API-call history for video %s", video_row.id, exc_info=True)

        # When not deploying, the pipeline ends here: script + video + download.
        if not deploy:
            logger.info(
                "=== Pipeline finished (video only): %s — skipping ad deployment ===",
                local_path,
            )
            return CreativePipelineResult(
                product_id=product_row.id,
                script_id=script_row.id,
                video_id=video_row.id,
                local_video_path=local_path,
                script_text=script.text,
                script_provider=script.provider,
                deployed=False,
            )

        # 4 + 5. Upload, then create creative + ad in the EXISTING ad group.
        ad_name = f"{product.name} - {file_name}"
        try:
            uploaded = self._ads.upload_video(local_path, file_name=file_name)
            result = self._ads.create_creative_and_ad(
                platform_video_id=uploaded.platform_video_id,
                ad_name=ad_name,
                landing_page_url=landing_page_url,
            )
            status = AdStatus.ACTIVE
            ad_row = self._ad_repo.create(
                product_id=product_row.id,
                video_id=video_row.id,
                platform=self._ads.name,
                campaign_id=self._campaign_id,
                adgroup_id=self._adgroup_id,
                platform_video_id=result.platform_video_id,
                creative_id=result.creative_id,
                ad_id=result.ad_id,
                name=ad_name,
                status=status,
            )
        except Exception:
            # Record the failed attempt so it is visible, then re-raise.
            logger.exception("Ad creation failed for '%s'", product.name)
            self._ad_repo.create(
                product_id=product_row.id,
                video_id=video_row.id,
                platform=self._ads.name,
                campaign_id=self._campaign_id,
                adgroup_id=self._adgroup_id,
                platform_video_id=None,
                creative_id=None,
                ad_id=None,
                name=ad_name,
                status=AdStatus.FAILED,
            )
            raise

        logger.info("=== Creative pipeline finished: ad_id=%s ===", result.ad_id)
        return CreativePipelineResult(
            product_id=product_row.id,
            script_id=script_row.id,
            video_id=video_row.id,
            local_video_path=local_path,
            script_text=script.text,
            script_provider=script.provider,
            deployed=True,
            ad_row_id=ad_row.id,
            platform_video_id=result.platform_video_id,
            creative_id=result.creative_id,
            ad_id=result.ad_id,
        )
